// frontend/src/utils/lucideIconMap.js
import {
  Wrench,
  Zap,
  Droplets,
  Hammer,
  Paintbrush,
  Shield,
  Star,
  CheckCircle,
  MessageCircle,
  Navigation,
  Filter,
  Search,
  MoreVertical,
  AlertCircle,
  TrendingUp,
  Award,
  Target,
  User,
  Phone,
  Mail,
  Clock,
  DollarSign,
  LogOut,
  Settings,
  ArrowRight,

  Users,
  X,
  Bell,
  MapPin, 
  Info, 
  XCircle 
  ,
  IndianRupee
} from 'lucide-react';

export const lucideIconMap = {
  Wrench: Wrench,
  Zap: Zap,
  Droplets: Droplets,
  Hammer: Hammer,
  Paintbrush: Paintbrush,
  Shield: Shield,
  Star: Star,
  CheckCircle: CheckCircle,
  MessageCircle: MessageCircle,
  Navigation: Navigation,
  Filter: Filter,
  Search: Search,
  MoreVertical: MoreVertical,
  AlertCircle: AlertCircle,
  TrendingUp: TrendingUp,
  Award: Award,
  Target: Target,
  User: User,
  Phone: Phone,
  Mail: Mail,
  Clock: Clock,
  IndianRupee : IndianRupee,
  LogOut: LogOut,
  Settings: Settings,
  ArrowRight: ArrowRight,
  Users: Users,
  X: X,
  Bell: Bell,
  MapPin: MapPin,
  Info: Info,
  XCircle: XCircle,
  plumbing: Droplets, 
  electrical: Zap,
  carpentry: Hammer,
  painting: Paintbrush,
  hvac: Wrench, 
  security: Shield, 
  electronics: Zap, 
  appliances: Wrench, 
  automotive: Shield,
  other: Wrench, 
};

export const getLucideIcon = (iconName, fallbackIcon = Wrench) => {
  return lucideIconMap[iconName] || fallbackIcon;
};